# Ubuntu 24.04
FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
ARG FS_VERSION=8.2.0
ARG UBUNTU_VERSION=ubuntu24

# Basics + libs
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget ca-certificates \
    python3 python3-pip \
 && rm -rf /var/lib/apt/lists/*

# Install FreeSurfer
RUN wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/${FS_VERSION}/freesurfer_${UBUNTU_VERSION}-${FS_VERSION}_amd64.deb && \
    apt-get update && \
    apt-get install -y ./freesurfer_${UBUNTU_VERSION}-${FS_VERSION}_amd64.deb && \
    rm -f freesurfer_${UBUNTU_VERSION}-${FS_VERSION}_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

# Env
ENV FREESURFER_HOME=/usr/local/freesurfer/${FS_VERSION} \
    FS_LICENSE=/usr/local/freesurfer/${FS_VERSION}/license.txt \
    PATH=/usr/local/freesurfer/${FS_VERSION}/bin:$PATH